### ISSUE TITLE
Docker version fails to start

### ISSUE THREAD

**Issue by dohnto** [achannarasappa/ticker#128]
**Describe the bug**
Following README and using containarized version & cannot start the ticker

**To Reproduce**
```
$ docker run -it --rm achannarasappa/ticker
Unable to find image 'achannarasappa/ticker:latest' locally
latest: Pulling from achannarasappa/ticker
4c0d98bf9879: Pull complete 
e4407f2427ee: Pull complete 
Digest: sha256:6aa544d9fce3b14ff129a44c1162191ab7bcb4108b305f9aa0411bd72038c8ca
Status: Downloaded newer image for achannarasappa/ticker:latest
panic: interface conversion: interface {} is nil, not []string

goroutine 1 [running]:
github.com/achannarasappa/ticker/internal/currency.transformResponseCurrencyPairs(0x0, 0x0, 0x0, 0x98c98e, 0x3, 0xc0004dc2d0, 0x0, 0x0)
	/home/runner/work/ticker/ticker/internal/currency/currency.go:83 +0x2df
github.com/achannarasappa/ticker/internal/currency.getCurrencyPairSymbols(0x0, 0x0, 0xc00006fec0, 0xc00006fef0, 0xc00006ff20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/ticker/ticker/internal/currency/currency.go:99 +0x396
github.com/achannarasappa/ticker/internal/currency.GetCurrencyRates(0x0, 0x0, 0xc00006fec0, 0xc00006fef0, 0xc00006ff20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/ticker/ticker/internal/currency/currency.go:108 +0xbf
github.com/achannarasappa/ticker/internal/cli.getReference(0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/ticker/ticker/internal/cli/cli.go:114 +0xf2
github.com/achannarasappa/ticker/internal/cli.GetContext(0xa45140, 0xd31c88, 0xc000001200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/ticker/ticker/internal/cli/cli.go:72 +0x2a5
github.com/achannarasappa/ticker/cmd.initConfig()
	/home/runner/work/ticker/ticker/cmd/root.go:58 +0x10a
github.com/spf13/cobra.(*Command).preRun(0xcf6ac0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:880 +0x49
github.com/spf13/cobra.(*Command).execute(0xcf6ac0, 0xc00001e1d0, 0x0, 0x0, 0xcf6ac0, 0xc00001e1d0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:816 +0x14f
github.com/spf13/cobra.(*Command).ExecuteC(0xcf6ac0, 0x44570a, 0xcae140, 0xc000042778)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/achannarasappa/ticker/cmd.Execute()
	/home/runner/work/ticker/ticker/cmd/root.go:33 +0x31
main.main()
	/home/runner/work/ticker/ticker/main.go:6 +0x25

```

**Expected behavior**
Start of the ap

**Environment (please complete the following information):**
 - OS: linux
 - ticker Version: 
```
$ docker inspect achannarasappa/ticker
[
    {
        "Id": "sha256:85d534765efcd086afb26b235d641b200c7968f5f9a47fc0ecda0f228cc0d375",
        "RepoTags": [
            "achannarasappa/ticker:latest"
        ],
        "RepoDigests": [
            "achannarasappa/ticker@sha256:6aa544d9fce3b14ff129a44c1162191ab7bcb4108b305f9aa0411bd72038c8ca"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-02-16T01:34:05.315493682Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm-256color"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": {
                "/.ticker.yaml": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/ticker"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.created": "2021-02-16T01:32:12Z",
                "org.opencontainers.image.revision": "1f16ba6f34523e50f74b7c79672ff5043f5b0236",
                "org.opencontainers.image.source": "https://github.com/achannarasappa/ticker",
                "org.opencontainers.image.title": "ticker",
                "org.opencontainers.image.version": "3.1.5"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 9143190,
        "VirtualSize": 9143190,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/655f50ff0684f422c7c2d8e74ea111b6b93f6db958fb04a1005ee64492148e43/diff",
                "MergedDir": "/var/lib/docker/overlay2/7807f11df243809f705ab75da83e73eef71d72fef0a92d69fd53af7378c1addb/merged",
                "UpperDir": "/var/lib/docker/overlay2/7807f11df243809f705ab75da83e73eef71d72fef0a92d69fd53af7378c1addb/diff",
                "WorkDir": "/var/lib/docker/overlay2/7807f11df243809f705ab75da83e73eef71d72fef0a92d69fd53af7378c1addb/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:1119ff37d4a9531330e3b8487863ee8ae0308337351be9d5f8bb38f80790acd9",
                "sha256:a62061c9dbb3f320c5d20901af2a151e90170d6be530cb238bc5c4a9dc3ec785"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
```

**Comment by dohnto** [comment]
Ah, this only happens when no arguments/config is passed. In that case just a helpful message would be appreciated for newcommers to not abandon it after first unsuccessful try.

**Comment by achannarasappa** [comment]
Thanks for reporting this

Not sure why but a locally, built image works fine but the one on docker hub fails with the error you reported. I'll have a closer look - this should definitely be fixed.

**Comment by achannarasappa** [comment]
In the latest version, I see this is working:

`docker pull achannarasappa/ticker:latest && docker run -it --rm achannarasappa/ticker:latest`
